#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [0]:
import numpy as np

arr = np.array([7, 8, 4, 5, 1, 2])

Using slicing print the elements from index 3 to the end of the array.



In [4]:
print(arr[3:])

[5 1 2]


Using slicing print all the elements except the last one.



In [9]:
print(arr[:-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [10]:
print(arr[1:4])

[8 4 5]


Reshape the array into a 3 rows and 2 cols (3,2).



In [0]:
newarr= arr.reshape(3,2)

Print all the array elements one by one (iterating).



In [48]:
for i in newarr:
  for x in i:
    print(x)

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [0]:
arr2=np.array([0, 6, 9])

Join the two arrays.



In [50]:
arrconc=np.concatenate((arr,arr2))
print(arrconc)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [70]:
filter_arr = []
for element in arrconc:
  if element %2==1:
    filter_arr.append(True)
  else:
    filter_arr.append(False) 
arrodd= arrconc[filter_arr]     
print(arrodd)

[7 5 1 9]


Sort the joined array elements.



In [71]:
print(np.sort(arrodd))

[1 5 7 9]


Store in an array the names of the months.



In [0]:
months=np.array(["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"])

Split the months array in 4 periods of 3 elements each one.



In [73]:
months2= months.reshape(4,3)
print(months2)

[['Enero' 'Febrero' 'Marzo']
 ['Abril' 'Mayo' 'Junio']
 ['Julio' 'Agosto' 'Septiembre']
 ['Octubre' 'Noviembre' 'Diciembre']]


Create an array with genre information ['F','M','F','F','M','F'].



In [0]:
genre= np.array(['F', 'M', 'F', 'F', 'M', 'F'])

Find the indexes where the value is F.



In [75]:
x=np.where(genre == 'F')
print(x)

(array([0, 2, 3, 5]),)


Store in an array the age information [18,20,19,23,19,20].



In [0]:
age= np.array([18,20,19,23,19,20])

Create a filter array with values < 20.



In [77]:
filter_arr = []
for element in age:
  if element <20:
    filter_arr.append(True)
  else:
    filter_arr.append(False) 
agefilt= age[filter_arr]     
print(agefilt)

[18 19 19]


Change the 3 index element with a value of 22



In [78]:
age[3] =22
print(age)

[18 20 19 22 19 20]


Print the 4 index element.

In [79]:
print(age[4])

19
